### PR TITLE
Add OpenDota Explorer script

### PR DESCRIPTION
**Pull request by howardchung**
* Added a script that fetches data from the [OpenDota Explorer](https://www.opendota.com/explorer)
  * Fetches the unpicked heroes too (as rows with 0 matches), but `heroes.py` doesn't handle this at the moment so I skip those rows.  The advantage is that the heroes list does not need to be updated regularly as new heroes are added in order to find the unpicked heroes (e.g. it's currently missing Monkey King)
  * Tournament ID is hardcoded to Kiev Major (5157) in the SQL query, but this could be made configurable/passable on the command line.
  * Skips the need to copy/paste tabular data since it fetches the data directly
* Added `.gitignore` for .pyc files

### CODE REVIEW

**Comment by chrisarena** [comment]
Hi @howardchung, thanks for this. Can you add a line to the readme on how to find the leagueid for a specific tournament (say, TI4), and then parameterize that with an input() call for the sql query?

**Comment by howardchung** [comment]
There are a few ways to get the ID:
* From the Explorer UI (https://www.opendota.com/explorer): Fill out the league field and then open the SQL editor to check the leagueid
* From the source data (http://api.opendota.com/api/leagues): Ctrl+F for the league in question, e.g.
```
{
"leagueid": 5157,
"ticket": "econ/leagues/kiev_major_2017",
"banner": "econ/leagues/kiev_major_2017_ingame",
"tier": "premium",
"name": "Kiev Major"
},
```
* Find the league on Dotabuff or similar and get the leagueid from the URL, e.g. https://www.dotabuff.com/esports/leagues/5157

Should I list all of these methods?

**Comment by howardchung** [comment]
Updated.

I made it a command line parameter: `python opendota.py {leagueid}` and put all three methods of getting leagueid in the README.

I also added Monkey King to the heroes list.

**Comment by howardchung** [comment]
Any update?

**Comment by howardchung** [comment]
I integrated this as well into the Explorer UI as "WR lower bound", so it's easier to compute this stat for any given range of matches.

Example for EPICENTER 2:
https://www.opendota.com/explorer?group=hero&league=5353&minDate=2017-06-01T07%3A00%3A00.000Z

**Pull request merged**
